# Generated by Django 4.0.3 on 2022-03-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Customer',
        ),
    ]
